[pytest]
addopts = --import-mode=importlib
pythonpath = .
filterwarnings =
    ignore:unclosed database:ResourceWarning
    ignore:Setting per-request cookies:DeprecationWarning:starlette.testclient
    ignore::jwt.InsecureKeyLengthWarning
