services:
  app:
    image: ghcr.io/soulwaxx/cashflow-manager:1.2.3
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    ports:
      - "80:8080"
    volumes:
      - ./data:/app/data
    env_file: .env
    restart: unless-stopped
